In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
file_path = r"C:\Users\FUJITSU\Downloads\olx_car_data_csv.csv"
cars_data = pd.read_csv(file_path)

In [9]:
cars_data.head()

Brand Condition    Fuel  KMs Driven        Model      Price  \
0  Toyota      Used  Diesel         1.0        Prado  2100000.0   
1  Suzuki      Used  Petrol    100000.0        Bolan   380000.0   
2  Suzuki      Used     CNG     12345.0        Bolan   340000.0   
3  Suzuki      Used  Petrol     94000.0         Alto   535000.0   
4  Toyota      Used  Petrol    100000.0  Corolla XLI  1430000.0   

  Registered City Transaction Type    Year  
0         Karachi             Cash  1997.0  
1         Karachi             Cash  2006.0  
2         Karachi             Cash  1998.0  
3         Karachi             Cash  2010.0  
4         Karachi             Cash  2013.0

In [10]:
cars_data.shape

(10577, 9)

In [11]:
cars_data.isnull().sum()

Brand                793
Condition            792
Fuel                 931
KMs Driven           853
Model                934
Price                  1
Registered City     1826
Transaction Type     931
Year                 852
dtype: int64

In [12]:
cars_data.dropna(inplace=True)

In [13]:
cars_data.shape

(8748, 9)

In [14]:
cars_data.duplicated().sum()


np.int64(340)

In [15]:
cars_data.duplicated().sum()

np.int64(340)

In [16]:
cars_data.drop_duplicates(inplace=True)

In [17]:
cars_data.shape

(8408, 9)

In [18]:
cars_data

Brand Condition    Fuel  KMs Driven        Model      Price  \
0      Toyota      Used  Diesel         1.0        Prado  2100000.0   
1      Suzuki      Used  Petrol    100000.0        Bolan   380000.0   
2      Suzuki      Used     CNG     12345.0        Bolan   340000.0   
3      Suzuki      Used  Petrol     94000.0         Alto   535000.0   
4      Toyota      Used  Petrol    100000.0  Corolla XLI  1430000.0   
...       ...       ...     ...         ...          ...        ...   
10572  Suzuki      Used  Petrol     10000.0   Cultus VXR   495000.0   
10573  Suzuki      Used  Petrol     30000.0     Margalla   385000.0   
10574  Suzuki      Used     CNG     90000.0   Cultus VXR   660000.0   
10575  Suzuki      Used  Petrol     25000.0   Cultus VXL   750000.0   
10576   Honda      Used     CNG    123456.0    Civic EXi   230000.0   

      Registered City Transaction Type    Year  
0             Karachi             Cash  1997.0  
1             Karachi             Cash  2006.0  
2             Karachi             Cash  1998.0  
3             Karachi             Cash  2010.0  
4             Karachi             Cash  2013.0  
...               ...              ...     ...  
10572         Karachi             Cash  2004.0  
10573         Karachi             Cash  1996.0  
10574         Karachi             Cash  2010.0  
10575         Karachi             Cash  2012.0  
10576         Karachi             Cash  1989.0  

[8408 rows x 9 columns]

In [19]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8408 entries, 0 to 10576
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Brand             8408 non-null   object 
 1   Condition         8408 non-null   object 
 2   Fuel              8408 non-null   object 
 3   KMs Driven        8408 non-null   float64
 4   Model             8408 non-null   object 
 5   Price             8408 non-null   float64
 6   Registered City   8408 non-null   object 
 7   Transaction Type  8408 non-null   object 
 8   Year              8408 non-null   float64
dtypes: float64(3), object(6)
memory usage: 656.9+ KB


In [20]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("======================")

Unique values of Brand
['Toyota' 'Suzuki' 'Honda' 'Daihatsu' 'Mitsubishi' 'KIA' 'Other Brands'
 'Nissan' 'BMW' 'Mazda' 'Chevrolet' 'Daewoo' 'Hyundai' 'FAW' 'Mercedes'
 'Classic & Antiques' 'Lexus' 'Audi' 'Range Rover' 'Changan' 'Porsche']
Unique values of Condition
['Used' 'New']
Unique values of Fuel
['Diesel' 'Petrol' 'CNG' 'Hybrid' 'LPG']
Unique values of KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
Unique values of Model
['Prado' 'Bolan' 'Alto' 'Corolla XLI' 'Corrolla Altis' 'Cultus VXL'
 'Civic VTi' 'Khyber' 'Liana' 'Passo' 'Civic Prosmetic' 'Civic EXi'
 'Charade' 'Pajero Mini' 'Margalla' 'City IVTEC' 'Classic' 'Other'
 'Corolla GLI' 'Cultus VXR' 'Dayz Highway Star' 'Mehran VX' 'Vitz'
 'Mehran VXR' 'Carry' 'Cultus VX' 'Baleno' 'Mira'
 'Civic VTi Oriel Prosmatec' 'Cuore' 'Corolla 2.0 D' 'Corolla XE' 'Surf'
 'FX' 'City IDSI' 'Premio' 'Sprinter' '3 Series' 'Hilux' 'Lancer' 'Swift'
 'Estima' 'Vamos' 'Starlet' 'Prius' 'Joy' '323' 'Racer' 'Su

In [21]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip()

In [ ]:
def clean_data(value):
 #   value = value.split(' ')[0]
  #  value = value.strip()
   # if value == '':
    #    value = 0
    #return float(value)

In [22]:
get_brand_name('Toyota')

'Toyota'

In [23]:
cars_data['Brand'] = cars_data['Brand'].apply(get_brand_name)

In [24]:
cars_data['Brand'].unique()

array(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
       'Other', 'Nissan', 'BMW', 'Mazda', 'Chevrolet', 'Daewoo',
       'Hyundai', 'FAW', 'Mercedes', 'Classic', 'Lexus', 'Audi', 'Range',
       'Changan', 'Porsche'], dtype=object)

In [25]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("======================")

Unique values of Brand
['Toyota' 'Suzuki' 'Honda' 'Daihatsu' 'Mitsubishi' 'KIA' 'Other' 'Nissan'
 'BMW' 'Mazda' 'Chevrolet' 'Daewoo' 'Hyundai' 'FAW' 'Mercedes' 'Classic'
 'Lexus' 'Audi' 'Range' 'Changan' 'Porsche']
Unique values of Condition
['Used' 'New']
Unique values of Fuel
['Diesel' 'Petrol' 'CNG' 'Hybrid' 'LPG']
Unique values of KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
Unique values of Model
['Prado' 'Bolan' 'Alto' 'Corolla XLI' 'Corrolla Altis' 'Cultus VXL'
 'Civic VTi' 'Khyber' 'Liana' 'Passo' 'Civic Prosmetic' 'Civic EXi'
 'Charade' 'Pajero Mini' 'Margalla' 'City IVTEC' 'Classic' 'Other'
 'Corolla GLI' 'Cultus VXR' 'Dayz Highway Star' 'Mehran VX' 'Vitz'
 'Mehran VXR' 'Carry' 'Cultus VX' 'Baleno' 'Mira'
 'Civic VTi Oriel Prosmatec' 'Cuore' 'Corolla 2.0 D' 'Corolla XE' 'Surf'
 'FX' 'City IDSI' 'Premio' 'Sprinter' '3 Series' 'Hilux' 'Lancer' 'Swift'
 'Estima' 'Vamos' 'Starlet' 'Prius' 'Joy' '323' 'Racer' 'Sunny' 'Accord'
 'Zest' 'A

In [26]:
cars_data['Brand'].replace(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
       'Other', 'Nissan', 'BMW', 'Mazda', 'Chevrolet', 'Daewoo',
       'Hyundai', 'FAW', 'Mercedes', 'Classic', 'Lexus', 'Audi', 'Range',
       'Changan', 'Porsche'],
                          [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
                          ,inplace=True)

C:\Users\FUJITSU\AppData\Local\Temp\ipykernel_15140\2758656943.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['Brand'].replace(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
C:\Users\FUJITSU\AppData\Local\Temp\ipykernel_15140\2758656943.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_dow

In [27]:
cars_data['Condition'].unique()

array(['Used', 'New'], dtype=object)

In [31]:
cars_data['Condition'] = cars_data['Condition'].replace(['Used', 'New'], [1, 2])

In [29]:
cars_data['Fuel'].unique()

array(['Diesel', 'Petrol', 'CNG', 'Hybrid', 'LPG'], dtype=object)

In [32]:
 cars_data['Fuel'] = cars_data['Fuel'].replace(['Diesel', 'Petrol', 'CNG', 'Hybrid', 'LPG'], [1, 2, 3, 4, 5])

In [33]:
cars_data['Model'].unique()

array(['Prado', 'Bolan', 'Alto', 'Corolla XLI', 'Corrolla Altis',
       'Cultus VXL', 'Civic VTi', 'Khyber', 'Liana', 'Passo',
       'Civic Prosmetic', 'Civic EXi', 'Charade', 'Pajero Mini',
       'Margalla', 'City IVTEC', 'Classic', 'Other', 'Corolla GLI',
       'Cultus VXR', 'Dayz Highway Star', 'Mehran VX', 'Vitz',
       'Mehran VXR', 'Carry', 'Cultus VX', 'Baleno', 'Mira',
       'Civic VTi Oriel Prosmatec', 'Cuore', 'Corolla 2.0 D',
       'Corolla XE', 'Surf', 'FX', 'City IDSI', 'Premio', 'Sprinter',
       '3 Series', 'Hilux', 'Lancer', 'Swift', 'Estima', 'Vamos',
       'Starlet', 'Prius', 'Joy', '323', 'Racer', 'Sunny', 'Accord',
       'Zest', 'AD Van', 'APV', 'March', 'Pride', 'Sportage',
       'Terios Kid', 'Santro', 'Fit', 'V2', 'City Aspire',
       'Civic VTi Oriel', 'BR-V', 'Kei', 'Probox', 'Hijet', '86', 'Yaris',
       'Aygo', 'Rush', 'Dayz', 'Fortuner', 'Every', 'Camry', 'Aqua',
       'Corolla Assista', 'Sera', 'Acty', 'Moco', 'Wagon R', 'Smart',
       'Demio

In [35]:
cars_data['Model'] = cars_data['Model'].replace(
        ['Prado', 'Bolan', 'Alto', 'Corolla XLI', 'Corrolla Altis', 'Cultus VXL', 'Civic VTi', 'Khyber', 'Liana', 'Passo',
        'Civic Prosmetic', 'Civic EXi', 'Charade', 'Pajero Mini', 'Margalla', 'City IVTEC', 'Classic', 'Other', 'Corolla GLI',
        'Cultus VXR', 'Dayz Highway Star', 'Mehran VX', 'Vitz', 'Mehran VXR', 'Carry', 'Cultus VX', 'Baleno', 'Mira',
        'Civic VTi Oriel Prosmatec', 'Cuore', 'Corolla 2.0 D', 'Corolla XE', 'Surf', 'FX', 'City IDSI', 'Premio', 'Sprinter',
        '3 Series', 'Hilux', 'Lancer', 'Swift', 'Estima', 'Vamos', 'Starlet', 'Prius', 'Joy', '323', 'Racer', 'Sunny', 'Accord',
        'Zest', 'AD Van', 'APV', 'March', 'Pride', 'Sportage', 'Terios Kid', 'Santro', 'Fit', 'V2', 'City Aspire',
        'Civic VTi Oriel', 'BR-V', 'Kei', 'Probox', 'Hijet', '86', 'Yaris', 'Aygo', 'Rush', 'Dayz', 'Fortuner', 'Every', 'Camry', 'Aqua',
        'Corolla Assista', 'Sera', 'Acty', 'Moco', 'Wagon R', 'Smart', 'Demio', 'Corona', 'Every Wagon', 'Civic Hybrid', 'Duet', 'Vezel',
        'Corolla Axio', 'City Vario', 'Corolla Fielder', 'Palette Sw', 'Platz', 'Lancer Evolution', 'Move', 'Gx Series', '5 Series',
        '240 Gd', 'Mira Cocoa', 'Wingroad', 'Belta', 'Atrai Wagon', 'Minicab Bravo', 'Allion', 'Blue Bird', 'Exclusive', 'N Wgn',
        'CT200h', 'Spectra', 'Beat', 'Mark II', 'Airwave', 'Supra', 'Ek Wagon', 'EK Custom', 'Lite Ace', '120 Y', 'Harrier',
        'Pixis Epoch', '626', 'Galant', 'Sonica', 'Carol Eco', 'Accent', 'IST', 'Land Cruiser', 'Palette', 'Juke', 'Potohar', 'CR-V',
        'Clipper', 'Sirius', 'Roox', '350Z', 'Pajero', 'Vitara', 'Alto Lapin', 'Wagon R Stingray', 'Prius Alpha', 'Minica', 'Cast',
        'Carol', 'Hustler', 'S Class', 'Boon', 'Jimny', 'Fj Cruiser', 'X-PV', 'Esse', 'Mirage', 'RX8', 'Carisma', 'iQ', 'Ek Sport',
        'CLK Class', 'Note', 'Stream', 'Carrier', 'Town Ace', 'I', 'N Box', 'Excel', 'B2200', 'Tundra', 'Scrum', 'Celica', 'Van', 'C Class',
        'Pickup', 'Kizashi', 'Freed', 'RX Series', 'Life', 'Otti', 'Spacia', 'Cervo', 'X5 Series', '200 D', 'Patrol', 'Acura',
        'Crown', 'Copen', 'Scrum Wagon', 'Charmant', 'Mark X', 'Spike', 'Vogue', 'Axela', '929', 'Ravi', 'Noah', 'Jade Hybrid', 'Tanto',
        'X Trail', 'EK Space Custom', 'Cielo', 'I Mivec', 'N One', 'i8', 'S660', 'Tiida', 'CR-Z', 'Verossa', 'Flair Wagon', 'Grace Hybrid',
        'E Class', 'Wish', 'L300', 'Auris', 'Cayenne', 'Silverado', 'Insight', 'Thats', 'C-HR', 'Familia Van', 'Jimny Sierra',
        'D Series', 'Escudo', 'Vanette', 'Rvr', 'LX Series', '250 D', 'Cami', 'Bluebird Sylphy', 'Pino', 'Ignis', 'A4', 'Wake', 'Spark',
        'Sirion', 'Q7', 'Zest Spark', 'Cruze', 'Avanza', 'Flair', 'ISIS', 'Cross Road', '7 Series', 'Matiz', 'Pulsar', 'Ciaz', 'A6',
        'Sonata', '6 Series', 'Cressida', 'Solio', 'Alphard Hybrid', 'Azwagon', 'Rav4', 'Toyo Ace'],
        [i for i in range(1, 250)]
    ).infer_objects(copy=False)

In [36]:
cars_data['Registered City'].unique()

array(['Karachi', 'Hyderabad', 'Bagh', 'Sukkar', 'Bahawalnagar', 'Lahore',
       'Askoley', 'Khanpur', 'Quetta', 'Karak', 'Islamabad', 'Sialkot',
       'Pakpattan', 'Lasbela', 'Sukkur', 'Rawalpindi', 'Bahawalpur',
       'Ali Masjid', 'Multan', 'Khaplu', 'Tank', 'Badin', 'Rahimyar Khan',
       'Chilas', 'Kasur', 'Khushab', 'Vehari', 'Chitral', 'Khanewal',
       'Attock', 'Larkana', 'Bela', 'Khairpur'], dtype=object)

In [38]:
cars_data['Registered City'] = cars_data['Registered City'].replace(
    ['Karachi', 'Hyderabad', 'Bagh', 'Sukkar', 'Bahawalnagar', 'Lahore',
     'Askoley', 'Khanpur', 'Quetta', 'Karak', 'Islamabad', 'Sialkot',
     'Pakpattan', 'Lasbela', 'Sukkur', 'Rawalpindi', 'Bahawalpur',
     'Ali Masjid', 'Multan', 'Khaplu', 'Tank', 'Badin', 'Rahimyar Khan',
     'Chilas', 'Kasur', 'Khushab', 'Vehari', 'Chitral', 'Khanewal',
     'Attock', 'Larkana', 'Bela', 'Khairpur'],
    list(range(1, 34))
).infer_objects(copy=False)

In [39]:
cars_data['Transaction Type'].unique()

array(['Cash', 'Installment/Leasing'], dtype=object)

In [41]:
cars_data['Transaction Type'] = cars_data['Transaction Type'].replace(
    ['Cash', 'Installment/Leasing'],
    [1, 2]
).infer_objects(copy=False)

In [42]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8408 entries, 0 to 10576
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Brand             8408 non-null   int64  
 1   Condition         8408 non-null   int64  
 2   Fuel              8408 non-null   int64  
 3   KMs Driven        8408 non-null   float64
 4   Model             8408 non-null   int64  
 5   Price             8408 non-null   float64
 6   Registered City   8408 non-null   int64  
 7   Transaction Type  8408 non-null   int64  
 8   Year              8408 non-null   float64
dtypes: float64(3), int64(6)
memory usage: 656.9 KB


In [43]:
cars_data.reset_index(inplace=True)

In [44]:
cars_data.drop(columns=['index'], inplace=True)

In [45]:
cars_data

Brand  Condition  Fuel  KMs Driven  Model      Price  Registered City  \
0         1          1     1         1.0      1  2100000.0                1   
1         2          1     2    100000.0      2   380000.0                1   
2         2          1     3     12345.0      2   340000.0                1   
3         2          1     2     94000.0      3   535000.0                1   
4         1          1     2    100000.0      4  1430000.0                1   
...     ...        ...   ...         ...    ...        ...              ...   
8403      2          1     2     10000.0     20   495000.0                1   
8404      2          1     2     30000.0     15   385000.0                1   
8405      2          1     3     90000.0     20   660000.0                1   
8406      2          1     2     25000.0      6   750000.0                1   
8407      3          1     3    123456.0     12   230000.0                1   

      Transaction Type    Year  
0                    1  1997.0  
1                    1  2006.0  
2                    1  1998.0  
3                    1  2010.0  
4                    1  2013.0  
...                ...     ...  
8403                 1  2004.0  
8404                 1  1996.0  
8405                 1  2010.0  
8406                 1  2012.0  
8407                 1  1989.0  

[8408 rows x 9 columns]

In [46]:
for col in cars_data.columns:
    print('------------')
    print(col)
    print(cars_data[col].unique())

------------
Brand
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
------------
Condition
[1 2]
------------
Fuel
[1 2 3 4 5]
------------
KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
------------
Model
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 

In [47]:
cars_data.isnull().sum()

Brand               0
Condition           0
Fuel                0
KMs Driven          0
Model               0
Price               0
Registered City     0
Transaction Type    0
Year                0
dtype: int64

In [48]:
input_data = cars_data.drop(columns=['Price'])
output_data =cars_data['Price']

In [49]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [50]:
model = LinearRegression()

In [51]:
model.fit(x_train, y_train)

LinearRegression()

In [52]:
predict = model.predict(x_test)

In [53]:
predict

array([ 718831.92519302,  565070.83635559,  -27460.64158438, ...,
       1367433.21566212,  579643.2484007 , 1078648.28219059])

In [54]:
x_train.head(1)

Brand  Condition  Fuel  KMs Driven  Model  Registered City  \
2180      2          1     2        12.0      3                1   

      Transaction Type    Year  
2180                 1  2004.0

In [60]:
input_data_model = pd.DataFrame(
    [[4,2,2,100000,56,6,1,2021.0]],
    columns=['Brand','Condition','Fuel','KMs Driven','Model','Registered City','Transaction Type','Year'])

In [61]:
input_data_model

Brand  Condition  Fuel  KMs Driven  Model  Registered City  \
0      4          2     2      100000     56                6   

   Transaction Type    Year  
0                 1  2021.0

In [62]:
model.predict(input_data_model)

array([1786112.07473862])

In [65]:
import pickle as pk

In [66]:
pk.dump(model,open('model.pkl','wb'))